CREATE TABLE ex_requerente (
    ID_REQUERENTE INT UNSIGNED NOT NULL AUTO_INCREMENT,
    CPF_REQUERENTE VARCHAR(11) NOT NULL,
    NOME_REQUERENTE VARCHAR(256) NOT NULL,
    ENDERECO_REQUERENTE VARCHAR(128),
    NMENDERECO_REQUERENTE INT,
    RG_REQUERENTE VARCHAR(16),
    TIPO_REQUERENTE INT,
    BAIRRO_REQUERENTE VARCHAR(128),
    CIDADE_REQUERENTE VARCHAR(64),
    DATA_NASC_REQUERENTE DATETIME,
    ESTADO_CIVIL_REQUERENTE INT,
    NOME_CONJUGUE VARCHAR(256),
    CONTATO_REQUERENTE VARCHAR(16),
    EMAIL_REQUERENTE VARCHAR(256),
    NACIONALIDADE_REQUERENTE VARCHAR(64),
    PRIMARY KEY (ID_REQUERENTE)
);
