CREATE TABLE sigagc.gc_acesso (
    ID_ACESSO BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    NOME_ACESSO VARCHAR(64) NOT NULL,
    PRIMARY KEY (ID_ACESSO)
);

CREATE TABLE sigagc.gc_arquivo (
    ID_CONTEUDO BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    TITULO VARCHAR(128),
    CLASSIFICACAO VARCHAR(128),
    CONTEUDO MEDIUMBLOB,
    CONTEUDO_TIPO VARCHAR(32),
    PRIMARY KEY (ID_CONTEUDO)
);

CREATE TABLE sigagc.gc_tipo_informacao (
    ID_TIPO_INFORMACAO BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    NOME_TIPO_INFORMACAO VARCHAR(64) NOT NULL,
    ARQUIVO BIGINT UNSIGNED,
    PRIMARY KEY (ID_TIPO_INFORMACAO),
    FOREIGN KEY (ARQUIVO) REFERENCES sigagc.gc_arquivo(ID_CONTEUDO)
);

CREATE TABLE sigagc.gc_configuracao (
    ID_CONFIGURACAO_GC BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    ID_TIPO_INFORMACAO BIGINT UNSIGNED,
    PRIMARY KEY (ID_CONFIGURACAO_GC),
    FOREIGN KEY (ID_TIPO_INFORMACAO) REFERENCES sigagc.gc_tipo_informacao(ID_TIPO_INFORMACAO)
);

CREATE TABLE sigagc.gc_tipo_tag (
    ID_TIPO_TAG BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    NOME_TIPO_TAG VARCHAR(64) NOT NULL,
    PRIMARY KEY (ID_TIPO_TAG)
);

CREATE TABLE sigagc.gc_tag (
    ID_TAG BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    CATEGORIA VARCHAR(32),
    TITULO VARCHAR(256),
    ID_TIPO_TAG BIGINT UNSIGNED NOT NULL,
    PRIMARY KEY (ID_TAG),
    FOREIGN KEY (ID_TIPO_TAG) REFERENCES sigagc.gc_tipo_tag(ID_TIPO_TAG)
);

CREATE TABLE sigagc.gc_informacao (
    ID_INFORMACAO BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    DT_ELABORACAO_FIM DATETIME,
    ANO YEAR,
    NUMERO INT,
    HIS_DT_INI DATETIME,
    HIS_DT_FIM DATETIME,
    ID_TIPO_INFORMACAO BIGINT UNSIGNED NOT NULL,
    ID_INFORMACAO_PAI BIGINT UNSIGNED,
    ID_ORGAO_USUARIO INT UNSIGNED NOT NULL,
    ID_ACESSO BIGINT UNSIGNED NOT NULL,
    ID_ACESSO_EDICAO BIGINT UNSIGNED NOT NULL,
    ID_PESSOA_TITULAR INT UNSIGNED NOT NULL,
    ID_LOTACAO_TITULAR INT UNSIGNED NOT NULL,
    ID_ARQUIVO BIGINT UNSIGNED NOT NULL,
    ID_GRUPO INT UNSIGNED,
    HIS_IDC_INI INT UNSIGNED NOT NULL,
    PRIMARY KEY (ID_INFORMACAO),
    FOREIGN KEY (ID_TIPO_INFORMACAO) REFERENCES sigagc.gc_tipo_informacao(ID_TIPO_INFORMACAO),
    FOREIGN KEY (ID_INFORMACAO_PAI) REFERENCES sigagc.gc_arquivo(ID_CONTEUDO),
    FOREIGN KEY (ID_ORGAO_USUARIO) REFERENCES corporativo.cp_orgao_usuario(ID_ORGAO_USU),
    FOREIGN KEY (ID_ACESSO) REFERENCES sigagc.gc_acesso(ID_ACESSO),
    FOREIGN KEY (ID_ACESSO_EDICAO) REFERENCES sigagc.gc_acesso(ID_ACESSO),
    FOREIGN KEY (ID_PESSOA_TITULAR) REFERENCES corporativo.dp_pessoa(ID_PESSOA),
    FOREIGN KEY (ID_LOTACAO_TITULAR) REFERENCES corporativo.dp_lotacao(ID_LOTACAO),
    FOREIGN KEY (ID_ARQUIVO) REFERENCES sigagc.gc_arquivo(ID_CONTEUDO),
    FOREIGN KEY (ID_GRUPO) REFERENCES corporativo.cp_grupo(ID_GRUPO),
    FOREIGN KEY (HIS_IDC_INI) REFERENCES corporativo.cp_identidade(ID_IDENTIDADE)
);

CREATE TABLE sigagc.gc_informacao_x_tag (
    ID_INFORMACAO BIGINT UNSIGNED NOT NULL,
    ID_TAG BIGINT UNSIGNED NOT NULL,
    PRIMARY KEY (ID_INFORMACAO, ID_TAG),
    FOREIGN KEY (ID_INFORMACAO) REFERENCES sigagc.gc_informacao(ID_INFORMACAO),
    FOREIGN KEY (ID_TAG) REFERENCES sigagc.gc_tag(ID_TAG)
);

CREATE TABLE sigagc.gc_tipo_movimentacao (
    ID_TIPO_MOVIMENTACAO BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    NOME_TIPO_MOVIMENTACAO VARCHAR(64) NOT NULL,
    PRIMARY KEY (ID_TIPO_MOVIMENTACAO)
);

CREATE TABLE sigagc.gc_papel (
    ID_PAPEL BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    DESC_PAPEL VARCHAR(256) NOT NULL,
    PRIMARY KEY (ID_PAPEL)
);

CREATE TABLE sigagc.gc_movimentacao (
    ID_MOVIMENTACAO BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    DESCRICAO VARCHAR(256),
    HIS_DT_INI DATETIME,
    ID_TIPO_MOVIMENTACAO BIGINT UNSIGNED NOT NULL,
    ID_INFORMACAO BIGINT UNSIGNED NOT NULL,
    ID_MOVIMENTACAO_REF BIGINT UNSIGNED,
    ID_MOVIMENTACAO_CANCELADORA BIGINT UNSIGNED,
    ID_PESSOA_ATENDENTE INT UNSIGNED,
    ID_LOTACAO_ATENDENTE INT UNSIGNED,
    ID_PAPEL BIGINT UNSIGNED,
    ID_GRUPO INT UNSIGNED,
    ID_PESSOA_TITULAR INT UNSIGNED,
    ID_LOTACAO_TITULAR INT UNSIGNED,
    ID_CONTEUDO BIGINT UNSIGNED,
    HIS_IDC_INI INT UNSIGNED NOT NULL,
    PRIMARY KEY (ID_MOVIMENTACAO),
    FOREIGN KEY (ID_TIPO_MOVIMENTACAO) REFERENCES sigagc.gc_tipo_movimentacao(ID_TIPO_MOVIMENTACAO),
    FOREIGN KEY (ID_INFORMACAO) REFERENCES sigagc.gc_informacao(ID_INFORMACAO),
    FOREIGN KEY (ID_MOVIMENTACAO_REF) REFERENCES sigagc.gc_movimentacao(ID_MOVIMENTACAO),
    FOREIGN KEY (ID_MOVIMENTACAO_CANCELADORA) REFERENCES sigagc.gc_movimentacao(ID_MOVIMENTACAO),
    FOREIGN KEY (ID_PESSOA_ATENDENTE) REFERENCES corporativo.dp_pessoa(ID_PESSOA),
    FOREIGN KEY (ID_LOTACAO_ATENDENTE) REFERENCES corporativo.dp_lotacao(ID_LOTACAO),
    FOREIGN KEY (ID_PAPEL) REFERENCES sigagc.gc_papel(ID_PAPEL),
    FOREIGN KEY (ID_GRUPO) REFERENCES corporativo.cp_grupo(ID_GRUPO),
    FOREIGN KEY (ID_PESSOA_TITULAR) REFERENCES corporativo.dp_pessoa(ID_PESSOA),
    FOREIGN KEY (ID_LOTACAO_TITULAR) REFERENCES corporativo.dp_lotacao(ID_LOTACAO),
    FOREIGN KEY (ID_CONTEUDO) REFERENCES sigagc.gc_arquivo(ID_CONTEUDO),
    FOREIGN KEY (HIS_IDC_INI) REFERENCES corporativo.cp_identidade(ID_IDENTIDADE)
);

-- Função de remoçao de acentos
DELIMITER //
CREATE FUNCTION sigagc.remove_acento(textvalue varchar(10000)) RETURNS varchar(10000) DETERMINISTIC
BEGIN
    SET @textvalue = textvalue;
    -- ACCENTS
    SET @withaccents = 'ŠšŽžÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÑÒÓÔÕÖØÙÚÛÜÝŸÞàáâãäåæçèéêëìíîïñòóôõöøùúûüýÿþƒ';
    SET @withoutaccents = 'SsZzAAAAAAACEEEEIIIINOOOOOOUUUUYYBaaaaaaaceeeeiiiinoooooouuuuyybf';
    SET @count = length(@withaccents);

    WHILE @count > 0 DO
        SET @textvalue = replace(@textvalue, substring(@withaccents, @count, 1), substring(@withoutaccents, @count, 1));
        SET @count = @count - 1;
    END WHILE;
    -- SPECIAL CHARS
    SET @special = '!@#$%¨&*()_+=§¹²³£¢¬"`´{[^~}]<,>.:;?/°ºª+*|\\''';
    SET @count = length(@special);

    WHILE @count > 0 DO
        SET @textvalue = replace(@textvalue, substring(@special, @count, 1), '');
        SET @count = @count - 1;
    END WHILE;

    RETURN @textvalue;
END;
//
DELIMITER ;


